# Generated by Django 5.2.8 on 2025-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userexpenseaccount_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
