# Generated by Django 5.2.8 on 2025-11-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_transaction_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', '🍔 Food & Dining'), ('Transport', '🚗 Transport'), ('Shopping', '🛍️ Shopping'), ('Bills', '💡 Bills & Utilities'), ('Entertainment', '🎬 Entertainment'), ('Health', '🏥 Health & Fitness'), ('Education', '📚 Education'), ('Other', '📦 Other')], default='Other', max_length=50),
        ),
    ]
