# Generated by Django 5.2.8 on 2025-11-18 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_transaction_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('subscription', '📱 Subscription'), ('emi', '💳 EMI'), ('loan', '🏦 Loan')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_date', models.IntegerField(help_text='Day of month (1-31)')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for subscriptions', null=True)),
                ('reminder_days', models.IntegerField(default=3, help_text='Remind X days before due date')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_deduct', models.BooleanField(default=False, help_text='Auto-create expense transaction on due date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Expense',
                'verbose_name_plural': 'Recurring Expenses',
                'db_table': 'recurring_expenses',
                'ordering': ['billing_date'],
            },
        ),
    ]
